### ISSUE TITLE
Ability to timeout retries after a specific amount of time has elapsed

### ISSUE THREAD

**Issue by farmery** [Moniepoint/dart-flow#18]
I think there will be a good number of usecases, where retries would be required to stop after a specific amount of time has elapsed.

This functionality will be nice to have

**Comment by donpaul120** [comment]
We can have this.

```dart
 flow((collector)  async {
    await 3.seconds;
   collector.emit('A');
})
.timeout(2.seconds);
```

ultimately if there are no emission within the specified timeout duration then an Exception will be thrown e.g TimeoutCancellationException.

i find this similar to kotlin's Flow.timeout also.

https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/timeout.html
