### ISSUE TITLE
Standardize Time Parameter Handling Using Duration Instead of Integers

### ISSUE THREAD

**Issue by farmery** [Moniepoint/dart-flow#25]
Currently, several methods and constructors in the Dart codebase accept delays, timeouts, and similar parameters as integers, with the assumption that these values represent milliseconds. This approach can lead to ambiguity and potential errors, especially in scenarios where durations are expected to be specified in different units or with greater precision.

I suggest replacing these integer parameters with the Duration class, which provides a clearer and more flexible way to represent time intervals . By utilizing Duration, developers can specify time durations in a more intuitive manner, including support for different units such as seconds, minutes, and hours.

**Comment by donpaul120** [comment]
I agree with this also i  think internally, though not to be exposed, we can also have the extension on integer for Duration. e.g 1.seconds, 2.milliseconds.

Just for internal development I find declaring or instantiating a Duration object quite a handful most times while testing. 

I don’t think exposing that is part of Flow’s current concern.
